data<-read.table("household_power_consumption.txt", sep=";",na.strings='?',header=TRUE,colClasses = "character")
data$Date<-as.Date(data$Date,"%d/%m/%Y")

a<-subset(data,Date==as.Date("2007-02-01")|Date==as.Date("2007-02-02"))
a$Global_active_power<-as.numeric(as.character(a$Global_active_power))
a$Time <- strptime(paste(a$Date,a$Time), "%Y-%m-%d %H:%M:%S")
with(a,plot(Time, Sub_metering_1,xlab="",ylab="Energy sub metering",type="n"))
with(a,lines(Time, Sub_metering_1,col="black"))
with(a,lines(Time, Sub_metering_2,col="red"))
with(a,lines(Time, Sub_metering_3,col="blue"))
legend("topright", lwd = 2, col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png,"plot3.png")
dev.off()
